blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions (Questions, Ideas & General Conversations)
    url: https://github.com/hyochan/expo-iap/discussions
    about: For questions, sharing ideas, and general conversations. Use Issues for bug reports and feature requests that need tracking with commits and PRs.
