name: Deploy Documentation

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.38' # Use specific version to avoid rate limiting

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-docs-${{ hashFiles('docs/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-docs-

      - name: Install dependencies
        run: |
          cd docs
          bun install

      - name: Build website
        run: |
          cd docs
          bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          force_orphan: true
